all:
	g++ -std=c++11 -I/usr/include -L/usr/local/lib -L/usr/X11R6/lib Matrix.cpp -o gltest -lglut -lGLU -lGL -lX11 -lXext  -lXi -lm
	###g++  -I/usr/include -L/usr/local/lib -L/usr/X11R6/lib Matrix.cpp -o gltest -lglut -lGLU -lGL -lX11 -lXext  -lXi -lm

clean:
	rm gltest -rf
